### PR TITLE
fix: secret reference update Ingress

### LINKED ISSUE #1777: bug: Deleting secret when using ingress tls will cause controller to crash
### Current Behavior

When using the tls of the ingress resource, deleting the secret will cause the controller to crash.

2edd6f1b0b7873f739627d10085d06b

The code that caused the crash:

https://github.com/apache/apisix-ingress-controller/blob/f9aba3945bef2a385ff8261d42e30599b144023c/pkg/providers/ingress/ingress.go#L579-L586

Ingress example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress-https
spec:
  ingressClassName: apisix
  tls:
  - hosts:
    - example.com
    secretName: example-secret
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
```

### Expected Behavior

It work.

### Error Logs

_No response_

### Steps to Reproduce

1. Deploy apisix-ingress-controller
2. Create a secret `example-secret`
3. Create a ingress tls with secret
```yaml
spec:
  tls:
  - hosts:
    - example.com
    secretName: example-secret
```
4. Delete secret `example-secret`

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`) 1.6.1
- Kubernetes cluster version (run `kubectl version`) 1.26.3
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`) Debian

### PR DESCRIPTION
**Pull request by lingsamuel**
### Type of change:

- [x] Bugfix

Fixes #1777

### What this PR does / why we need it:

Fix a bug that causes nil reference and secret change won't trigger Ingress resource sync.

### Pre-submission checklist:

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

File: pkg/providers/ingress/ingress.go [hunk 1]
```diff
@@ -131,7 +130,7 @@ func (c *ingressController) sync(ctx context.Context, ev *types.Event) error {
 	}
 
 	if err != nil {
-		if !k8serrors.IsNotFound(err) {
+		if !k8serrors.IsNotFound(err) || (k8serrors.IsNotFound(err) && ev.Type != types.EventDelete) {
```
Comment (AlinsRan) [inline pkg/providers/ingress/ingress.go:133]: There are two questions here
1. Events are not always up-to-date. We always retrieve the latest object, which may have been deleted. This logic can lead to infinite retries.
2. Redundant logic, same as line 138.

image

```go
if !k8serrors.IsNotFound(err) || (k8serrors.IsNotFound(err) && ev.Type != types.EventDelete) { return }
if ev.Type != types.EventDelete { return } # Redundant 

<==>

if !k8serrors.IsNotFound(err) { return }
if ev.Type != types.EventDelete { return }

```

File: pkg/providers/ingress/ingress.go [hunk 2]
```diff
@@ -152,6 +152,36 @@ func (c *ingressController) sync(ctx context.Context, ev *types.Event) error {
 		}
 		ing = ev.Tombstone.(kube.Ingress)
 	}
+	if ing == nil {
```
Comment (AlinsRan) [inline pkg/providers/ingress/ingress.go:155]: Same reason as above.
```golang
return nil
```

**Review by AlinsRan — CHANGES_REQUESTED** [review]

**Comment by AlinsRan** [comment]
When deleting a secret, does the SSL object of APISIX exist?
Missing e2e case for delete-secret?

**Review by tao12345666333 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]
