### PR TITLE
fix: trigger ApisixRoute event when service is created

### LINKED ISSUE #926: bug: we should create APISIX routes even if Service is created later
> https://github.com/apache/apisix-ingress-controller/blob/c9e0c965cd2226e2c44aa4e692a8bf57d1586aa3/pkg/ingress/apisix_route.go#L261-L271
> 
> We will delete this event from workqueue if we have an `ApisixRoute` resources without any valid backends. It is reasonable?

@cmssczy  This change is to fix the #810 and was introduced in #893 

**This does cause some problems.**

For example, create an ApisixRoute first, which references a service that does not exist.
But when a Service is created, the APISIX Ingress controller can't actually create a route.

_Originally posted by @tao12345666333 in https://github.com/apache/apisix-ingress-controller/issues/925#issuecomment-1072128249_

### PR DESCRIPTION
**Pull request by lingsamuel**
### Type of change:

Fixes #926

- [x] Bugfix

### CODE REVIEW

File: test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go [hunk 1]
```diff
@@ -576,6 +578,115 @@ spec:
...
+`, "httpbin-temp", 80)
+
+			assert.Nil(ginkgo.GinkgoT(), s.CreateVersionedApisixResource(apisixRoute), "creating ApisixRoute")
+			// We don't have service yet, so upstream==0
+			err := s.EnsureNumApisixRoutesCreated(0)
+			assert.Nil(ginkgo.GinkgoT(), err, "Checking number of routes")
+			err = s.EnsureNumApisixUpstreamsCreated(0)
+			assert.Nil(ginkgo.GinkgoT(), err, "Checking number of upstreams")
+			err = s.EnsureNumApisixPluginConfigCreated(0)
+			assert.Nil(ginkgo.GinkgoT(), err, "Checking number of pluginConfigs")
```
Comment (tao12345666333) [inline test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go:679]: Actually we don't create PluginConfig, so this can be deleted

File: pkg/ingress/apisix_route.go [hunk 2]
```diff
@@ -41,13 +43,20 @@ type apisixRouteController struct {
 	controller *Controller
 	workqueue  workqueue.RateLimitingInterface
 	workers    int
+
+	// svc meta key -> ApisixRoute name -> empty
+	// map[string]map[string]struct{}
+	svcLock sync.RWMutex
+	svcMap  map[string]map[string]struct{} //*sync.Map
```
[the remark this answers is not in the document]
Comment (lingsamuel) [reply pkg/ingress/apisix_route.go:50]: I would like to use more specific types instead of the untyped sync.Map.

File: pkg/kube/apisix_route.go [hunk 3]
```diff
@@ -35,6 +35,12 @@ type ApisixRouteLister interface {
 	V2beta3(string, string) (ApisixRoute, error)
 	// V2 gets the ApisixRoute in apisix.apache.org/v2.
 	V2(string, string) (ApisixRoute, error)
+	// V2beta2Lister gets the v2beta2 lister
+	V2beta2Lister() listersv2beta2.ApisixRouteLister
```
Comment (tao12345666333) [inline pkg/kube/apisix_route.go:39]: we don't need this?

File: pkg/kube/apisix_route.go [hunk 4]
```diff
@@ -78,6 +84,18 @@ type apisixRoute struct {
 	v2           *configv2.ApisixRoute
 }
 
+func (l *apisixRouteLister) V2beta2Lister() listersv2beta2.ApisixRouteLister {
+	return l.v2beta2Lister
+}
```
Comment (tao12345666333) [inline pkg/kube/apisix_route.go:89]: ditto

File: test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go [hunk 5]
```diff
@@ -576,6 +578,113 @@ spec:
...
+            timeoutSeconds: 2
+          readinessProbe:
+            failureThreshold: 3
+            initialDelaySeconds: 2
+            periodSeconds: 5
+            successThreshold: 1
+            tcpSocket:
+              port: 80
+            timeoutSeconds: 2
+          image: "localhost:5000/kennethreitz/httpbin"
```
Comment (AlinsRan) [inline test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go:622]: localhost:5000/kennethreitz/httpbin:dev

File: pkg/ingress/apisix_route.go [hunk 6]
```diff
@@ -82,9 +95,114 @@ func (c *apisixRouteController) runWorker(ctx context.Context) {
...
+			newObj = ar.V2()
+		}
+
+		// calculate diff, so we don't need to care about the event order
+		if old != nil {
+			for _, rule := range old.Spec.HTTP {
+				for _, backend := range rule.Backends {
+					oldBackends = append(oldBackends, backend.ServiceName)
+
+					delete(c.svcMap[old.Namespace+"/"+backend.ServiceName], old.Name)
```
Comment (AlinsRan) [inline pkg/ingress/apisix_route.go:175]: Does this conflict with line 198? There is no lock here.

File: pkg/ingress/apisix_route.go [hunk 7]
```diff
@@ -82,9 +95,114 @@ func (c *apisixRouteController) runWorker(ctx context.Context) {
...
+			newObj = ar.V2beta3()
+		}
+
+		// calculate diff, so we don't need to care about the event order
+		if old != nil {
+			for _, rule := range old.Spec.HTTP {
+				for _, backend := range rule.Backends {
+					oldBackends = append(oldBackends, backend.ServiceName)
+
+					delete(c.svcMap[old.Namespace+"/"+backend.ServiceName], old.Name)
```
Comment (AlinsRan) [inline pkg/ingress/apisix_route.go:142]: Does this conflict with line 198? There is no lock here.

File: pkg/ingress/apisix_route.go [hunk 8]
```diff
@@ -41,13 +42,19 @@ type apisixRouteController struct {
 	controller *Controller
 	workqueue  workqueue.RateLimitingInterface
 	workers    int
+
+	// svc meta key -> ApisixRoute name -> empty
+	svcLock sync.RWMutex
```
Comment (AlinsRan) [inline pkg/ingress/apisix_route.go:47]: No read lock。

File: pkg/ingress/apisix_route.go [hunk 9]
```diff
@@ -41,13 +42,19 @@ type apisixRouteController struct {
 	controller *Controller
 	workqueue  workqueue.RateLimitingInterface
 	workers    int
+
+	// svc meta key -> ApisixRoute name -> empty
```
Comment (AlinsRan) [inline pkg/ingress/apisix_route.go:46]: we should only maintain the `map` when the service is not exist? @tao12345666333

File: test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go (hunk 5 above)
Comment (lingsamuel) [reply test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go]: This image doesn't have such tag

File: pkg/ingress/apisix_route.go (hunk 9 above)
Comment (tao12345666333) [reply pkg/ingress/apisix_route.go:46]: no, the service can be modified.

Consider this one, when service be deleted and re-created, we also need the map

Comment (AlinsRan) [reply pkg/ingress/apisix_route.go:46]: OK.

**Review by tao12345666333 — APPROVED** [review]
LGTM

let's move forward.

**Review by gxthrj — APPROVED** [review]
